---
title: "Funding"

format:
    html: 
       embed-resources: true
---

Funding Opportunities (last updated December 2025)

+---------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| Option  | Funding Source                                                                                                                                                                                                                    | Funding                                                                                                                                 | Required objectives                                                                                                                                                                                                                                                                                                                   |         |
+---------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 1       | *open - submittals due* **January 20, 2026 (12:00 PST/ 15:00 EST)**                                                                                                                                                               | -   a **minimum of \$25,000**, and a **maximum of \$200,000**                                                                           | Projects which enable circular economy opportunities (e.g., nutrient recycling and/or recovery) for communities and/or sectors to achieve co-benefits, such as increased resilience to climate change, local economic growth, value chain efficiencies, etc.                                                                          |         |
|         |                                                                                                                                                                                                                                   |                                                                                                                                         |                                                                                                                                                                                                                                                                                                                                       |         |
|         | Canada Water Agency - [**Stream 2**](https://www.canada.ca/en/canada-water-agency/funding/ecoaction-community-program/stream2.html)                                                                                               | -   must be completed within the 2-year timeframe ending March 31, 2027                                                                 | \* besides municipal recipient, CWA allows for Domestic small for-profit entities (less than 100 employees) so applying directly is an option (vs. the FCMs below)                                                                                                                                                                    |         |
|         |                                                                                                                                                                                                                                   |                                                                                                                                         |                                                                                                                                                                                                                                                                                                                                       |         |
|         | Freshwater Sustainability and Innovation across Canada                                                                                                                                                                            | -   matching requirement:  minimum of 50% of the total value of the project must come from sources other than the Government of Canada. |                                                                                                                                                                                                                                                                                                                                       |         |
+---------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 2       | FCM [**Pilot: Net-Zero Transformation**](https://greenmunicipalfund.ca/funding/pilot-net-zero-transformation)                                                                                                                     | ·up to 50%\* of eligible costs                                                                                                          | Evaluate innovative GHG reduction solutions in real-world conditions.                                                                                                                                                                                                                                                                 |         |
|         |                                                                                                                                                                                                                                   |                                                                                                                                         |                                                                                                                                                                                                                                                                                                                                       |         |
|         |                                                                                                                                                                                                                                   | ·Up to a maximum of \$500,000                                                                                                           |                                                                                                                                                                                                                                                                                                                                       |         |
+---------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 3a      | FCM [**Business case: Organic Waste-to-Energy**](https://greenmunicipalfund.ca/funding/business-case-organic-waste-energy)                                                                                                        | ·up to 50%\* of eligible costs                                                                                                          | Assess viable waste-to-energy systems and business models for your project.                                                                                                                                                                                                                                                           |         |
|         |                                                                                                                                                                                                                                   |                                                                                                                                         |                                                                                                                                                                                                                                                                                                                                       |         |
|         |                                                                                                                                                                                                                                   | ·Up to a maximum of \$100,000                                                                                                           |                                                                                                                                                                                                                                                                                                                                       |         |
+---------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 3b      | FCM [**Study: Organic Waste-to-Energy**](https://greenmunicipalfund.ca/funding/study-organic-waste-energy)                                                                                                                        | ·up to 50%\* of eligible costs                                                                                                          | Outline the design of a proposed organic waste-to-energy system.  (3a recommended prior)                                                                                                                                                                                                                                              |         |
|         |                                                                                                                                                                                                                                   |                                                                                                                                         |                                                                                                                                                                                                                                                                                                                                       |         |
|         |                                                                                                                                                                                                                                   | ·Up to a maximum of \$200,000                                                                                                           |                                                                                                                                                                                                                                                                                                                                       |         |
+---------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 3c      | FCM [**Capital project: Organic Waste-to-Energy**](https://greenmunicipalfund.ca/funding/capital-project-organic-waste-energy)                                                                                                    | ·Combined grant and loan for up to 80% of eligible costs                                                                                | Construct, commission and begin operation of an organic waste-to-energy system. (3b required prior)                                                                                                                                                                                                                                   |         |
|         |                                                                                                                                                                                                                                   |                                                                                                                                         |                                                                                                                                                                                                                                                                                                                                       |         |
|         |                                                                                                                                                                                                                                   | ·Combined grant and loan up to a maximum of \$10 million                                                                                |                                                                                                                                                                                                                                                                                                                                       |         |
|         |                                                                                                                                                                                                                                   |                                                                                                                                         |                                                                                                                                                                                                                                                                                                                                       |         |
|         |                                                                                                                                                                                                                                   | ·Grant up to 15%\* of the loan amount                                                                                                   |                                                                                                                                                                                                                                                                                                                                       |         |
+---------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 4       | Scientific Research and Experimental Development (SR&ED) [tax incentives](https://www.canada.ca/en/revenue-agency/services/scientific-research-experimental-development-tax-incentive-program/what-are-sred-tax-incentives.html)  | deduction against corporate income                                                                                                      |                                                                                                                                                                                                                                                                                                                                       |         |
+---------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
| 5       | IESO Hydrogen Innovation Fund - due **11 February 2026**                                                                                                                                                                          | IESO contributes up to 50% of total eligible value (min. 1 million, max. 4.5 million)                                                   | Demonstration projects supporting the integration of low-carbon hydrogen into the electricity grid to increase electricity supply, capacity, or storage.                                                                                                                                                                              |         |
|         |                                                                                                                                                                                                                                   |                                                                                                                                         |                                                                                                                                                                                                                                                                                                                                       |         |
|         |                                                                                                                                                                                                                                   |                                                                                                                                         | 2.A.1 Demonstration of low-carbon hydrogen production technologies, such as water electrolysis, methane pyrolysis, steam methane reforming (SMR) with carbon capture/utilization, biomass gasification or reforming, and other novel low-carbon production methods can support decarbonization efforts of a hydrogen off-take partner |         |
+---------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+
